name: 暴力回滚

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:  # 添加权限声明
      contents: write
      workflows: write  # 允许修改工作流文件
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整历史记录

    - name: Reset to commit
      run: |
        git config --global user.email awm31415@163.com
        git config --global user.name HDILP
        git reset --hard 81c1e3
        
    - name: Force Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: ${{ github.ref_name }}  # 明确指定分支