name: 安装加密模块

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout actions
      uses: actions/checkout@v4.1.4

    - name: commit
      run: |
        git config --global user.email awm31415@163.com
        git config --global user.name HDILP
        git reset --hard 81c1e3
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
