name: Python application

on: 
  issues:
    types: [opened,edited]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
      uses: actions/checkout@v4.1.4

    - name: Set up Python 3.8
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.8
        
    - name: Update paper list
      env:
        GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}  # 从 GitHub Secrets 获取 API
      run: |
        python -m pip install requests        
        python post.py
        
    - name: commit
      run: |
        git config --global user.email awm31415@163.com
        git config --global user.name HDILP
        git add .
        git commit -m "update" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}


    - name: Close issue
      uses: actions-cool/issues-helper@v3
      with:
        actions: 'close-issue'
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.issue.number }}
        close-reason: 'completed'
