name: Web Screenshot via CLI
on:
  workflow_dispatch:
    inputs:
      url:
        description: '目标网页URL'
        required: true
      device:
        description: '模拟设备（如 iPhone 11）'
        required: false

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Playwright
        run: npm install -g playwright

      - name: Install Browsers
        run: npx playwright install --with-deps chromium

      - name: Capture Screenshot
        run: |
          npx playwright screenshot \
            --wait-for-timeout 5000 \  # 等待5秒加载
            --full-page \              # 截取完整页面
            --device "${{ github.event.inputs.device }}" \  # 设备模拟
            "${{ github.event.inputs.url }}" \
            screenshot.png

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: webpage-screenshot
          path: screenshot.png