name: Web Screenshot via CLI
on:
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Playwright
        run: npm install -g playwright

      - name: Install Browsers
        run: npx playwright install --with-deps chromium

      - name: Capture Screenshot
        run: |
          npx playwright screenshot --wait-for-timeout 5000 --viewport-size 1080,1440 https://kepuqv.hdilp.top/%E3%80%90%E9%9D%9E%E5%8E%9F%E5%88%9B%E3%80%91%E5%BE%95%E5%8D%A1%20SE4%20%E5%8D%AB%E6%98%9F%E9%80%9A%E8%AE%AF%E4%B8%AD%E7%AB%AF%E2%80%94%E5%B0%8F%E7%B1%B315Ultra/ screenshot.png

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webpage-screenshot
          path: screenshot.png
          compression-level: 0